Repository FromDoppler/emms25, pull requests merged in 2025-05, with the labels that each got.

#78 DS-5627 add two new capsules to library resources section
  components/sponsors/libraryResources/conferences.php
  pages/sponsors/library-resources.php
  src/img/conferences25/logos/eude-logo.png
  src/img/conferences25/logos/impulsate-logo.png
  src/img/conferences25/portada-eude.png
  src/img/conferences25/portada-impulsate.png
Labels: size/S

#79 DS-5628 Adjust internal speaker layout and spacing
  components/ecommerce/post/speaker-interna/event-recorded.php
  src/1.0.0/css/components/ecommerce/speaker-interna/event-recorded.css
  src/1.0.0/css/styles.css
Labels: size/L

#80 DS-5626 adjustments post deployment changes
  components/checkout/checkout-success.php
  components/schedule/speaker-grid/grid-days.php
  pages/ecommerce/post/ecommerce-registrado.php
  src/1.0.0/css/pages/checkout.css
Labels: size/M

#81 DS-5630 add capsules
  components/sponsors/libraryResources/conferences.php
  src/img/conferences25/logos/partnersacademy-logo.png
  src/img/conferences25/portada-impulsate.png
  src/img/conferences25/portada-partnersacademy.png
Labels: size/XS
