Repository FromDoppler/emms25, pull requests merged in 2025-03, with the labels that each got.

#18 DS-5532 fix & refactor conferences sponsors
  components/sponsors/libraryResources/conferences.php
Labels: size/L

#22 DS-5529 flicktify
  src/1.0.0/js/commonAnimations.js
Labels: size/M

#21 DS-5553 ediciones anteriores
  ediciones-anteriores.php
Labels: size/XS

#20 DS-5534 gtm refactor & hotjar
  components/gtm.php
  components/head.php
  config.php
Labels: size/M

#23 DS-5546 remove gtm from qa env
  pages/ecommerce/pre/ecommerce-registrado.php
  pages/ecommerce/pre/ecommerce.php
  pages/ecommerce/pre/home-registrado.php
  pages/ecommerce/pre/home.php
  pages/sponsors/library-resources.php
  sponsors-interna.php
  sponsors-promo.php
Labels: size/S

#24 DS-5556 sw firebase
  firebase-messaging-sw.js
Labels: size/XS

#26 chore/DS-5552-replace-placeholder
  components/register-form-component.php
  sponsors-promo.php
Labels: size/XS

#27 fix/DS-5551 change content
  components/sponsors/libraryResources/hero.php
  components/sponsors/libraryResources/registerModal.php
Labels: size/S

#28 DS-5554 refactor isRegistered
  components/ecommerce/pre/home/hello-module.php
  components/sponsors/libraryResources/conferences.php
  components/sponsors/libraryResources/registerModal.php
  components/sponsors/libraryResources/sponsorsList.php
  ecommerce-registrado.php
  ecommerce.php
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  index.php
  pages/sponsors/library-resources.php
  registrado.php
  services/register.php
  sponsors-registrado.php
  sponsors.php
Labels: size/M

#29 DS-5557 sponsors fix register modal
  components/ecommerce/pre/register-form.php
  components/sponsors/libraryResources/registerModal.php
  components/sponsorsList.php
  ediciones-anteriores.php
  pages/sponsors/library-resources.php
Labels: size/S

#30 refactor/DS-5547 refactor relay emails
  config.php
  services/EmailService.php
  services/register.php
  services/registerSponsor.php
  utils/EmailTemplateManager.php
  utils/Relay.php
Labels: size/XL

#31 DS-5561 add block id
  sponsors-promo.php
Labels: size/XS

#33 DS-5549 add resources module
  components/sponsors/libraryResources/resources/resourceCard.php
  components/sponsors/libraryResources/resources/resourceGrid.php
  pages/sponsors/library-resources.php
  src/1.0.0/css/pages/resources.css
  src/1.0.0/css/styles.css
  src/1.0.0/js/commonForm.js
  src/img/resources/resource-conversaciones.png
  src/img/resources/resource-email-mkt.png
  src/img/resources/resource-guia.png
  src/img/resources/resource-ia.png
Labels: size/L

#34 DS-5562 refactor register flow security
  config.php
  services/register.php
  services/restrictOriginAccess.php
Labels: size/L

#36 DS-5570 restrict origin in services
  services/EmailService.php
  services/clearCache.php
  services/functions.php
  services/getCountryNameAndCode.php
  services/getLogErrors.php
  services/getMediaPartners.php
  services/getPhase.php
  services/getRegisteredByEmail.php
  services/getSubscriptionsDoppler.php
Labels: size/S

#37 DS-5570 remove restrict from services
  services/EmailService.php
  services/clearCache.php
  services/functions.php
  services/getCountryNameAndCode.php
  services/getLogErrors.php
  services/getMediaPartners.php
  services/getPhase.php
  services/getRegisteredByEmail.php
  services/getSubscriptionsDoppler.php
  services/register.php
Labels: size/S

#38 DS-5549 change resources link
  components/sponsors/libraryResources/resources/resourceGrid.php
Labels: size/XS

#39 DS-5582 apply final content
  components/date-counter.php
  components/ecommerce/pre/companies-list.php
  components/ecommerce/pre/ecommerce/entry-plans.php
  components/ecommerce/pre/ecommerce/hello-module.php
  components/ecommerce/pre/ecommerce/hello-vip-module.php
  components/ecommerce/pre/ecommerce/video-ticketing.php
  components/ecommerce/pre/ecommerce/vip-features.php
  components/ecommerce/pre/register-withoutform.php
  components/ecommerce/schedule/schedule.php
  components/sponsors/libraryResources/conferences.php
  components/sponsors/libraryResources/sponsorsList.php
  pages/ecommerce/pre/ecommerce-registrado.php
  pages/sponsors/library-resources.php
  sponsors-promo.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/features.css
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/css/pages/sponsors-promo.css
  src/img/asset-estrella.png
  src/img/conferences25/logos/wextion-logo.png
  src/img/conferences25/logos/wrangler-logo.png
  src/img/conferences25/portada-capsula-wextion.png
  src/img/conferences25/portada-nicolas-castro.png
Labels: size/L

#40 DS-5581 refactor checkout components & pages
  checkout-success.php
  checkout.php
  components/checkout/checkout-success.php
  components/checkout/checkout.php
  components/checkout/faq.php
  config.php
  pages/checkout/checkout-success.php
  pages/checkout/checkout.php
Labels: size/L

#41 DS-5587 delete form field
  services/registerSponsor.php
  sponsors-promo.php
  src/1.0.0/js/sponsorsPromo.js
  utils/EmailTemplateManager.php
Labels: size/M

#42 DS-5585 feature new content
  components/checkout/checkout-success.php
  components/checkout/faq.php
  src/1.0.0/css/pages/checkout.css
  src/img/logos/logo-emms-ecommerce-dark.png
Labels: size/M

#43 DS-5581 stripe customer create flow
  components/checkout/checkout-success.php
  config.php
  stripe/controllers/StripeCustomersController.php
  stripe/createCustomer.php
  stripe/models/RegisteredDatabase.php
  stripe/models/StripeCustomersDatabase.php
  stripe/models/SubscriberDopplerList.php
  stripe/utils/SpreadSheetGoogle.php
  stripe/utils/sendEmail.php
  stripe/utils/toHex.php
Labels: size/L
