Repository FromDoppler/emms25, pull requests merged in 2025-04, with the labels that each got.

#45 DS-5590 pre deploy adjustments
  components/ecommerce/pre/companies-list.php
  components/ecommerce/pre/ecommerce/entry-plans.php
  components/ecommerce/pre/ecommerce/hello-vip-module.php
  components/ecommerce/schedule/mobile-carousel.php
  components/ecommerce/schedule/schedule.php
  components/sponsorsList.php
  pages/ecommerce/pre/ecommerce-registrado.php
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/js/toggleVipElements.js
Labels: size/L

#44 DS-5589 email pre vip
  utils/EmailTemplateManager.php
  utils/relay-templates/ecommerce/ecommerce-pre-template.html
  utils/relay-templates/ecommerce/ecommerce-vip-template.html
Labels: size/XXL

#47 DS-5594 post deploy fixes
  components/ecommerce/pre/ecommerce/video-ticketing.php
  components/ecommerce/schedule/mobile-carousel.php
  components/ecommerce/schedule/schedule.php
  components/ecommerce/schedule/showSpeakersByDay.php
  src/img/home/card-image-digitaltrends-post.png
Labels: size/S

#48 DS-5595 fix utms register free
  services/register.php
Labels: size/S

#50 DS-5596 utms vip flow
  components/checkout/checkout-success.php
  components/checkout/checkout.php
  stripe/controllers/StripeCustomersController.php
Labels: size/M

#51 DS-5599 refactor move form submission logic to submitHelpers.js
  src/1.0.0/js/common/submitForm.js
  src/1.0.0/js/common/submitHelpers.js
  src/1.0.0/js/common/switchForm.js
Labels: size/L

#52 [DS-5601] add Meta Pixel tracking on successful registration
  src/1.0.0/js/common/submitForm.js
  src/1.0.0/js/common/submitHelpers.js
Labels: size/S

#49 feat/DS-5475-new-schedule
  components/schedule/schedule-tabs/schedule-button.php
  components/schedule/schedule-tabs/schedule-buttons.php
  components/schedule/schedule-tabs/schedule-tabs-helper.php
  components/schedule/schedule-tabs/schedule-tabs.php
  components/schedule/schedule.php
  components/schedule/speaker-card/speaker-card-helper.php
  components/schedule/speaker-card/speaker-card.php
  components/schedule/speaker-card/speaker-cta.php
  components/schedule/speaker-card/speaker-image.php
  components/schedule/speaker-card/speaker-info.php
  components/schedule/speaker-card/speaker-modal/speaker-modal-social.php
  components/schedule/speaker-card/speaker-modal/speaker-modal.php
  components/schedule/speaker-card/speaker-ribon.php
  components/schedule/speaker-grid-helper.php
  components/schedule/speaker-grid.php
  pages/ecommerce/pre/ecommerce-registrado.php
  pages/ecommerce/pre/ecommerce.php
  src/1.0.0/css/components/schedule/schedule-tabs/schedule-tabs-index.css
  src/1.0.0/css/components/schedule/schedule-tabs/schedule-tabs.css
  src/1.0.0/css/components/schedule/schedule.css
  src/1.0.0/css/components/schedule/scheduleIndex.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-card-index.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-card.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-cta.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-hour.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-image.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-info.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-modal/speaker-modal-social.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-modal/speaker-modal.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-ribon.css
  src/1.0.0/css/components/schedule/speaker-grid/speakergrid.css
  src/1.0.0/css/styles.css
Labels: size/XXL

#53 DS-5604 init during
  components/ecommerce/during/benefit-icons.php
  components/ecommerce/during/central-video.php
  components/ecommerce/during/companies-list.php
  components/ecommerce/during/doppler-academy-banner.php
  components/ecommerce/during/ecommerce/certificate/certificate-modal.php
  components/ecommerce/during/ecommerce/certificate/certificate.js
  components/ecommerce/during/ecommerce/certificate/certificate.php
  components/ecommerce/during/ecommerce/certificate/certificateModal.js
  components/ecommerce/during/ecommerce/entry-plans.php
  components/ecommerce/during/ecommerce/event-live.php
  components/ecommerce/during/ecommerce/head.php
  components/ecommerce/during/ecommerce/hello-module.php
  components/ecommerce/during/ecommerce/hello-vip-module.php
  components/ecommerce/during/ecommerce/video-ticketing.php
  components/ecommerce/during/ecommerce/vip-features.php
  components/ecommerce/during/event-numbers.php
  components/ecommerce/during/faqs.php
  components/ecommerce/during/grid-event-types.php
  components/ecommerce/during/hellobar-vip.php
  components/ecommerce/during/hellobar.php
  components/ecommerce/during/home/head.php
  components/ecommerce/during/home/hello-module.php
  components/ecommerce/during/premium-content.php
  components/ecommerce/during/register-form.php
  components/ecommerce/during/register-withoutform.php
  components/ecommerce/during/speakers-carousel.php
  components/ecommerce/during/users-comments.php
  pages/ecommerce/during/ecommerce-registrado.php
  pages/ecommerce/during/ecommerce.php
  pages/ecommerce/during/home-registrado.php
  pages/ecommerce/during/home.php
Labels: size/XXL

#55 DS-5475 fix schedule post deployed
  components/schedule/schedule-tabs/schedule-tabs.php
  components/schedule/speaker-card/helpers/index.php
  components/schedule/speaker-card/helpers/speaker-button.php
  components/schedule/speaker-card/helpers/speaker-render.php
  components/schedule/speaker-card/helpers/speaker-utils.php
  components/schedule/speaker-card/speaker-button.php
  components/schedule/speaker-card/speaker-card-helper.php
  components/schedule/speaker-card/speaker-card.php
  components/schedule/speaker-card/speaker-cta.php
  components/schedule/speaker-card/speaker-info.php
  components/schedule/speaker-card/speaker-ribon.php
  components/schedule/speaker-grid.php
  components/schedule/speaker-grid/grid-days.php
Labels: size/L

#57 DS-5606 change email links
  utils/relay-templates/ecommerce/ecommerce-pre-template.html
Labels: size/XS

#56 DS-5605 email vip v2
  utils/relay-templates/ecommerce/ecommerce-vip-template.html
Labels: size/XL

#58 DS-5598 change content
  components/ecommerce/during/ecommerce/hello-vip-module.php
  components/ecommerce/pre/ecommerce/hello-vip-module.php
Labels: size/XS

#59 DS-5607 during content
  components/ecommerce/during/central-video.php
  components/ecommerce/during/ecommerce/certificate/certificate.php
  components/ecommerce/during/ecommerce/event-live.php
  components/ecommerce/during/faq-banner.php
  components/ecommerce/during/hellobar-vip.php
  components/ecommerce/during/hellobar.php
  components/ecommerce/during/home/hello-module.php
  components/ecommerce/during/premium-content.php
  components/ecommerce/during/register-form.php
  components/ecommerce/during/register-withoutform.php
  components/ecommerce/during/speakers-carousel.php
  components/ecommerce/pre/speakers-carousel.php
  components/event-card.php
  components/register-form-component.php
  components/schedule/schedule-tabs/schedule-tabs-helper.php
  components/schedule/schedule.php
  components/schedule/speaker-card/speaker-card.php
  components/schedule/speaker-grid.php
  components/schedule/speaker-grid/grid-days.php
  components/sponsorsList.php
  pages/ecommerce/during/ecommerce-registrado.php
  pages/ecommerce/during/ecommerce.php
  pages/ecommerce/during/home-registrado.php
  pages/ecommerce/during/home.php
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/hero-conference.css
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/info-banner/info-banner.css
  src/1.0.0/css/components/premium-content-banner.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/css/styles.css
  src/1.0.0/js/speakerCarrousel.js
Labels: size/XL

#62 DS-5616 final ux adjustments
  components/checkout/checkout-success.php
  components/ecommerce/during/central-video.php
  components/ecommerce/during/ecommerce/event-live.php
  components/ecommerce/during/ecommerce/vip-features.php
  components/ecommerce/during/hellobar-vip.php
  components/ecommerce/during/hellobar.php
  components/ecommerce/during/home/hello-module.php
  components/ecommerce/during/premium-content.php
  components/ecommerce/during/register-form.php
  components/ecommerce/during/speakers-carousel.php
  components/ecommerce/pre/ecommerce/entry-plans.php
  components/event-card.php
  components/register-form-component.php
  pages/ecommerce/during/home-registrado.php
  pages/ecommerce/during/home.php
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/hero-conference.css
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/premium-content-banner.css
Labels: size/L

#63 DS-5615 during email vip
  utils/relay-templates/ecommerce/ecommerce-during-vip-template.html
Labels: size/XXL

#64 DS-5614 during free email
  utils/relay-templates/ecommerce/ecommerce-during-template.html
Labels: size/XXL

#61 DS-5613 event certificate
  src/1.0.0/js/common/certificate.js
  textify/certificate-emms2025.php
  textify/certificate-emms2025qa.php
  textify/ecommerce/certificadoemms2025-ecommerce.png
  textify/ecommerce/certificadoemms2025-joseanmunoz.png
  textify/ecommerce/certificadoemms2025-laurabarreto.png
  textify/ecommerce/certificadoemms2025-luisbetancourt.png
  textify/ecommerce/certificadoemms2025-matiascarrera.png
  textify/ecommerce/certificadoemms2025-pablomoratinos.png
  textify/ecommerce/certificadoemms2025-xavierIdevik.png
Labels: size/L

#65 DS-5612 workshops emails
  utils/relay-templates/ecommerce/workshop/ecommerce-certificate-joseanmuñoz.html
  utils/relay-templates/ecommerce/workshop/ecommerce-certificate-laurabarreto.html
  utils/relay-templates/ecommerce/workshop/ecommerce-certificate-luisbetancourt.html
  utils/relay-templates/ecommerce/workshop/ecommerce-certificate-matiascarrera.html
  utils/relay-templates/ecommerce/workshop/ecommerce-certificate-pablomoratinos.html
  utils/relay-templates/ecommerce/workshop/ecommerce-certificate-xavierIdevik.html
Labels: size/XXL

#66 DS-5617 refactor seo flow & update content
  components/ecommerce/during/ecommerce/head.php
  components/ecommerce/during/ecommerce/seo-reg.php
  components/ecommerce/during/ecommerce/seo-unreg.php
  components/ecommerce/during/home/head.php
  components/ecommerce/during/home/seo-reg.php
  components/ecommerce/during/home/seo-unreg.php
  components/share.php
  pages/ecommerce/during/ecommerce-registrado.php
  pages/ecommerce/during/ecommerce.php
  pages/ecommerce/during/home-registrado.php
  pages/ecommerce/during/home.php
Labels: size/L

#67 DS-5608 init post
  components/ecommerce/post/central-video.php
  components/ecommerce/post/ecommerce/hello-module.php
  components/ecommerce/post/ecommerce/hello-vip-module.php
  components/ecommerce/post/ecommerce/seo-reg.php
  components/ecommerce/post/ecommerce/seo-unreg.php
  components/ecommerce/post/ecommerce/video-ticketing.php
  components/ecommerce/post/ecommerce/vip-features.php
  components/ecommerce/post/home/hello-module.php
  components/ecommerce/post/home/seo-reg.php
  components/ecommerce/post/home/seo-unreg.php
  components/ecommerce/post/register-form.php
  components/ecommerce/post/register-withoutform.php
  components/ecommerce/post/speaker-interna/event-recorded.php
  components/ecommerce/post/speaker-interna/promo-vip.php
  components/ecommerce/post/speakers-carousel.php
  pages/ecommerce/post/ecommerce-registrado.php
  pages/ecommerce/post/ecommerce.php
  pages/ecommerce/post/home-registrado.php
  pages/ecommerce/post/home.php
  pages/ecommerce/post/speaker-interna.php
Labels: size/XL

#70 DS-5620 fix mobile speaker card
  src/1.0.0/css/components/schedule/speaker-card/speaker-card.css
Labels: size/XS

#71 DS-5621 certificate script
  components/ecommerce/during/ecommerce/certificate/certificate.js
  descarga-certificado.php
  src/1.0.0/js/certificateWorkshop.js
Labels: size/L

#69 DS-5619 reprogramado transition workshops
  components/ecommerce/during/ecommerce/event-live.php
  src/1.0.0/css/components/hero-conference.css
Labels: size/S

#74 DS-5625 email post
  utils/EmailTemplateManager.php
  utils/relay-templates/ecommerce/ecommerce-post-vip-template.html
Labels: size/XXL

#76 DS-5624 email free post
  utils/relay-templates/ecommerce/ecommerce-post-template.html
Labels: size/XXL

#73 DS-5623 ecommerce post
  components/ecommerce/during/ecommerce/certificate/certificate-modal.php
  components/ecommerce/post/benefit-icons.php
  components/ecommerce/post/central-video.php
  components/ecommerce/post/companies-list.php
  components/ecommerce/post/doppler-academy-banner.php
  components/ecommerce/post/ecommerce/entry-plans.php
  components/ecommerce/post/ecommerce/hello-module.php
  components/ecommerce/post/ecommerce/hello-vip-module.php
  components/ecommerce/post/event-numbers.php
  components/ecommerce/post/faq-banner.php
  components/ecommerce/post/faqs.php
  components/ecommerce/post/grid-event-types.php
  components/ecommerce/post/hellobar-vip.php
  components/ecommerce/post/hellobar.php
  components/ecommerce/post/home/hello-module.php
  components/ecommerce/post/premium-content.php
  components/ecommerce/post/register-form copy.php
  components/ecommerce/post/register-form.php
  components/ecommerce/post/register-withoutform.php
  components/ecommerce/post/speakers-carousel.php
  components/ecommerce/post/users-comments.php
  components/event-card.php
  components/register-form-component.php
  components/schedule/schedule.php
  components/schedule/speaker-card/helpers/speaker-button.php
  components/schedule/speaker-card/speaker-button.php
  components/schedule/speaker-card/speaker-info.php
  components/schedule/speaker-grid.php
  components/schedule/speaker-grid/grid-days.php
  components/sponsorsList.php
  pages/ecommerce/post/ecommerce-registrado.php
  pages/ecommerce/post/ecommerce.php
  pages/ecommerce/post/home-registrado.php
  pages/ecommerce/post/home.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/certificate-modal.css
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-card.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-cta.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/general/constants.css
  src/1.0.0/css/pages/checkout.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/js/counterAnimation.js
Labels: size/XXL

#77 DS-5623 ecommerce post
  components/schedule/speaker-card/speaker-button.php
Labels: size/XS
