Repository FromDoppler/emms25, pull requests merged in 2025-09, with the labels that each got.

#135 DS-5786 pre digital trends layout
  components/digital-trends/pre/digital-trends/entry-plans.php
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/digital-trends/hello-vip-module.php
  components/digital-trends/pre/digital-trends/video-ticketing.php
  components/digital-trends/pre/digital-trends/vip-features.php
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/premium-content.php
  components/digital-trends/pre/register-form.php
  components/ecommerce/pre/ecommerce/vip-features.php
  components/ecommerce/schedule/showSpeakersByDay.php
  components/referral.php
  components/schedule/schedule-tabs/schedule-tabs-helper.php
  components/schedule/schedule-tabs/schedule-tabs.php
  components/schedule/schedule.php
  components/schedule/speaker-grid-helper.php
  components/schedule/speaker-grid.php
  components/schedule/speaker-grid/grid-days.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/features.css
  src/1.0.0/css/components/grid.css
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/components/referral.css
  src/1.0.0/css/components/users-comments.css
  src/1.0.0/css/general/buttons.css
  src/img/backgrounds/referral-bg.png
  src/img/referral/premios-mobile.png
  src/img/referral/premios.png
  src/img/referral/referral.png
Labels: size/XXL

#136 DS-5787 sponsors pre dt
  components/sponsors-promo/hero.php
Labels: size/XS

#137 DS-5789 digital trends vip purchase processing
  stripe/controllers/StripeCustomersController.php
  stripe/createCustomer.php
  stripe/models/SubscriberDopplerList.php
  stripe/utils/SpreadSheetGoogle.php
  utils/EmailTemplateManager.php
  utils/relay-templates/dt/dt-pre-vip-template.html
Labels: size/XXL

#139 DS-5779 remove fields
  utils/SpreadSheetGoogle.php
Labels: size/XS

#140 DS-5778 change modal logic
  components/modal/captor.js
  components/modal/extraDataCaptor.php
  components/modal/modal.css
  components/modal/openModal.js
  components/modal/scripts/modalConditions.js
  components/modal/scripts/modalIds.enum.js
  components/modal/scripts/modalQueueStore.js
Labels: size/L

#144 DS-5796 modal improvements
  components/digital-trends/pre/digital-trends/entry-plans.php
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/digital-trends/hello-vip-module.php
  components/digital-trends/pre/digital-trends/video-ticketing.php
  components/digital-trends/pre/digital-trends/vip-features.php
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/register-withoutform.php
  components/hello-bar.php
  components/modal/modal.css
  components/modal/partials/modal-extradata.php
  components/modal/partials/modal-vip.php
  components/register-form-component.php
  components/schedule/schedule.php
  components/schedule/speaker-card/helpers/speaker-button.php
  components/schedule/speaker-card/speaker-button.php
  components/schedule/speaker-card/speaker-image.php
  components/schedule/speaker-grid/grid-days.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/general/buttons.css
  src/img/gifs.png
  src/img/modals/persona-cupones.png
Labels: size/L

#157 DS-5824 autocomplete multiple forms
  src/1.0.0/js/autoCompleteUserForm.js
Labels: size/M

#160 DS-5817 during dt ux
  components/digital-trends/during/central-video.php
  components/digital-trends/during/digital-trends/certificate/certificate-modal.php
  components/digital-trends/during/digital-trends/certificate/certificate.js
  components/digital-trends/during/digital-trends/certificate/certificate.php
  components/digital-trends/during/digital-trends/certificate/certificateModal.js
  components/digital-trends/during/digital-trends/event-live.php
  components/digital-trends/during/digital-trends/video-ticketing.php
  components/digital-trends/during/digital-trends/vip-features.php
  components/digital-trends/during/home/head.php
  components/digital-trends/during/home/hello-module.php
  components/digital-trends/during/register-form.php
  components/digital-trends/during/register-withoutform.php
  components/digital-trends/pre/doppler-academy-banner.php
  components/hello-bar.php
  components/schedule/schedule.php
  pages/digital-trends/during/digital-trends-registrado.php
  pages/digital-trends/during/digital-trends.php
  src/1.0.0/css/components/calendar.css
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/hero-registration.css
Labels: size/XL
