Repository FromDoppler/emms25, pull requests merged in 2025-10, with the labels that each got.

#162 DS-5818 dt live trans
  components/digital-trends/during/digital-trends/event-live.php
  components/digital-trends/during/digital-trends/slides/register-free-slide.php
  components/digital-trends/during/digital-trends/slides/register-vip-slide.php
  components/digital-trends/during/register-form.php
  pages/digital-trends/during/combinations/dtr-during.php
  pages/digital-trends/during/combinations/dtr-transition.php
  pages/digital-trends/during/digital-trends-registrado.php
  pages/digital-trends/during/digital-trends.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/hero-conference.css
  src/1.0.0/css/components/hero-registration.css
  src/img/placas/par-de-tickets.png
  src/img/placas/tuercas.png
Labels: size/L

#161 DS-5832 Sistema de colas con Redis Streams para procesamiento asíncrono de suscripciones VIP
  .docker/config/php/Dockerfile
  .docker/db/EMMS25.sql
  .docker/docker-compose.yml
  .docker/readme.md
  config.php
  config/redis.php
  stripe/controllers/StripeCustomersController.php
  stripe/createCustomer.php
  stripe/models/RegisteredDatabase.php
  stripe/models/StripeCustomersDatabase.php
  stripe/models/StripeCustomersJobsDatabase.php
  stripe/models/SubscriberDopplerList.php
  stripe/workers/EmailWorker.php
  stripe/workers/ListWorker.php
  stripe/workers/README.md
  stripe/workers/SpreadsheetWorker.php
  stripe/workers/core/BaseWorker.php
  stripe/workers/core/RedisManager.php
  utils/Logger.php
Labels: size/XXL

#165 DS-5836 landing checkout ux
  components/checkout-lp/checkout-success.php
  components/modal/partials/modal-vip.php
  components/schedule/schedule-tabs/schedule-button.php
  components/schedule/schedule-tabs/schedule-tabs-helper.php
  components/schedule/schedule.php
  components/schedule/speaker-card/speaker-ribon.php
  components/schedule/speaker-grid.php
  pages/checkout-lp/checkout-success.php
  pages/checkout-lp/checkout.php
  pages/checkout-lp/components/entry-plans.php
  pages/checkout-lp/components/grid-event-types.php
  pages/checkout-lp/components/hello-module.php
  pages/checkout-lp/components/video-ticketing.php
  pages/checkout-lp/components/vip-features.php
  pages/checkout-lp/landing.php
  src/1.0.0/css/components/prices-plans.css
  src/1.0.0/css/components/schedule/speaker-card/speaker-ribon.css
Labels: size/XL

#167 DS-5839 Integrate Stripe checkout flow and backend caching improvements
  components/checkout-lp/checkout-success.php
  components/checkout-lp/checkout.php
  components/checkout/checkout.php
  pages/checkout-lp/checkout.php
  pages/checkout/checkout-success.php
  pages/checkout/checkout.php
  services/create-checkout-session.php
  services/fetch-session-status.php
Labels: size/L

#171 DS-5841 remove speaker buttons
  components/schedule/speaker-card/helpers/speaker-button.php
  components/schedule/speaker-card/speaker-button.php
Labels: size/S

#170 DS-5839 fix checkout-success instegration
  components/checkout-lp/checkout-success.php
  pages/checkout-lp/checkout-success.php
Labels: size/XS
