Repository FromDoppler/emms25, pull requests merged in 2025-02, with the labels that each got.

#4 DS-5494 register home
  components/ecommerce/pre/doppler-academy-banner.php
  components/navbar.php
  pages/ecommerce/pre/home-registrado.php
  registrado.php
  src/1.0.0/css/components/doppler-academy-banner.css
Labels: size/M

#2 DS-5492 sql emms25
  .docker/db/EMMS25.sql
Labels: size/S

#7 DS-5526 refactor sponsors page
  components/academyBanner.php
  components/sponsors/libraryResources/academyBanner.php
  components/sponsors/libraryResources/conferences.php
  components/sponsors/libraryResources/hero.php
  components/sponsors/libraryResources/registerModal.php
  components/sponsors/libraryResources/sponsorsList.php
  pages/sponsors/library-resources.php
  sponsors.php
Labels: size/L

#9 DS-5496 commerce logged
  components/ecommerce/pre/ecommerce/hello-module.php
  components/ecommerce/pre/ecommerce/hello-vip-module.php
  pages/ecommerce/pre/ecommerce-registrado.php
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/pages/digital-trends.css
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/css/pages/sponsors-promo.css
Labels: size/L

#12 DS-5498 register flow
  config.php
  src/1.0.0/js/commonForm.js
  src/1.0.0/js/newDate.js
  src/1.0.0/js/toggleVipElements.js
Labels: size/L

#13 DS-5501 earlybirds ecommerce email
  utils/relay-templates/ecommerce/ecommerce-early-template.html
  utils/relay-templates/ecommerce/ecommerce-pre-template.html
  utils/relay-templates/ecommerce/old/ecommerce-during-template.html
  utils/relay-templates/ecommerce/old/ecommerce-during-vip-template.html
  utils/relay-templates/ecommerce/old/ecommerce-post-template.html
  utils/relay-templates/ecommerce/old/ecommerce-post-vip-template.html
  utils/relay-templates/ecommerce/old/ecommerce-pre-template.html
  utils/relay-templates/ecommerce/old/ecommerce-vip-template.html
Labels: size/XXL

#14 DS-5502 config earlybirds ecommerce email
  utils/Relay.php
Labels: size/XS

#15 DS-5503 apply final content
  components/academyBanner.php
  components/ecommerce/pre/doppler-academy-banner.php
  components/ecommerce/pre/home/hello-module.php
  components/ecommerce/pre/speakers-carousel.php
  components/ecommerce/pre/users-comments.php
  components/event-card.php
  components/footer.php
  components/navbar-reg.php
  components/sponsors/libraryResources/academyBanner.php
  ecommerce-registrado.php
  ecommerce.php
  ediciones-anteriores-registrado.php
  index.php
  pages/ecommerce/pre/ecommerce-registrado.php
  registrado.php
  sponsors-promo.php
  src/1.0.0/css/components/doppler-academy-banner.css
  src/1.0.0/css/components/frequent-questions.css
  src/1.0.0/css/pages/sponsors.css
Labels: size/L

#16 DS-5528 apply seo content
  components/ecommerce/pre/ecommerce/head.php
  components/ecommerce/pre/home/head.php
  components/share.php
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
  share-2025.png
Labels: size/M

#17 DS-5530 feedback demo
  components/ecommerce/pre/central-video.php
  components/ecommerce/pre/ecommerce/hello-module.php
  components/ecommerce/pre/faqs.php
  components/ecommerce/pre/grid-event-types.php
  components/ecommerce/pre/hellobar.php
  components/ecommerce/pre/home/hello-module.php
  components/ecommerce/pre/speakers-carousel.php
  components/ecommerce/pre/users-comments.php
  components/footer.php
  components/navbar-reg.php
  components/navbar-unreg.php
  components/navbar.php
  components/sponsors/libraryResources/registerModal.php
  pages/ecommerce/pre/ecommerce.php
  pages/sponsors/library-resources.php
  sponsors-promo.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/css/components/date-counter.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/grid.css
  src/img/icons/icono-tiktok.svg
  src/img/logos--white/logo-canva.png
  src/img/logos--white/logo-google.png
  src/img/logos--white/logo-mercatitlan.png
  src/img/logos--white/logo-youtube.png
  src/img/logos/logo-airbnb.png
  src/img/logos/logo-amvo.png
  src/img/logos/logo-asociacion-marketing-espana.png
  src/img/logos/logo-banco-frances.png
  src/img/logos/logo-bigbox.png
  src/img/logos/logo-capece.png
  src/img/logos/logo-crehana.png
  src/img/logos/logo-doofinder.png
  src/img/logos/logo-easycommerce.png
  src/img/logos/logo-ecommerce-efectivo.png
  src/img/logos/logo-linkedin.png
  src/img/logos/logo-marketing-4ecommerce.png
  src/img/logos/logo-metricool.png
  src/img/logos/logo-semrush.png
  src/img/logos/logo-vtex.png
  src/img/logos/logo-woocomerce.png
  src/img/people--gradient/alina-pineda.png
  src/img/people--gradient/diana.png
  src/img/people--gradient/diego-dagnino.png
  src/img/people--gradient/facundo-dacunto.png
  src/img/people--gradient/juan-lombana.png
  src/img/people--gradient/julia-rayeb.png
  src/img/people--gradient/marcos-westphalen.png
  src/img/people--gradient/ricardo-tayer-img.png
Labels: size/L
