Repository FromDoppler/emms25, pull requests merged in 2025-07, with the labels that each got.

#82 DS-5685 update content
  components/ecommerce/post/home/hello-module.php
  components/ecommerce/post/register-form.php
  src/1.0.0/css/components/hero-registration.css
Labels: size/XS

#84 DS-5686 update scripts
  package.json
Labels: size/XS

#86 DS-5728 add structure data for quotes
  components/ecommerce/post/users-comments.php
Labels: size/L

#88 DS-5735 dt initial commit
  components/digital-trends/checkout/checkout-success.php
  components/digital-trends/checkout/checkout.php
  components/digital-trends/checkout/faq.php
  components/digital-trends/pre/benefit-icons.php
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/companies-list.php
  components/digital-trends/pre/digital-trends/entry-plans.php
  components/digital-trends/pre/digital-trends/head.php
  components/digital-trends/pre/digital-trends/hello-module.php
  components/digital-trends/pre/digital-trends/hello-vip-module.php
  components/digital-trends/pre/digital-trends/video-ticketing.php
  components/digital-trends/pre/digital-trends/vip-features.php
  components/digital-trends/pre/doppler-academy-banner.php
  components/digital-trends/pre/event-numbers.php
  components/digital-trends/pre/faqs.php
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/hellobar-vip.php
  components/digital-trends/pre/hellobar.php
  components/digital-trends/pre/home/head.php
  components/digital-trends/pre/home/hello-module.php
  components/digital-trends/pre/premium-content.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/register-withoutform.php
  components/digital-trends/pre/speakers-carousel.php
  components/digital-trends/pre/users-comments.php
  digital-trends-registrado.php
  digital-trends.php
  pages/digital-trends/pre/checkout-success.php
  pages/digital-trends/pre/checkout.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/digital-trends.php
  pages/digital-trends/pre/home-registrado.php
  pages/digital-trends/pre/home.php
Labels: size/XXL

#91 DS-5738 rename css to bem
  components/digital-trends/pre/home/hello-module.php
  components/ecommerce/during/home/hello-module.php
  components/ecommerce/post/home/hello-module.php
  components/ecommerce/pre/home/hello-module.php
  src/1.0.0/css/pages/home.css
Labels: size/L

#89 DS-5735 fix- paths
  index.php
  pages/digital-trends/pre/home-registrado.php
  pages/digital-trends/pre/home.php
  registrado.php
Labels: size/S
