Repository FromDoppler/emms25, pull requests merged in 2025-08, with the labels that each got.

#93 DS-5738 new home layout
  components/digital-trends/pre/central-video.php
  components/digital-trends/pre/companies-list.php
  components/digital-trends/pre/faqs.php
  components/digital-trends/pre/hellobar-vip.php
  components/digital-trends/pre/hellobar.php
  components/digital-trends/pre/home/hello-module.php
  components/digital-trends/pre/premium-content.php
  components/digital-trends/pre/speakers-carousel.php
  components/digital-trends/pre/users-comments.php
  components/ecommerce/during/hellobar-vip.php
  components/ecommerce/during/hellobar.php
  components/ecommerce/post/hellobar-vip.php
  components/ecommerce/post/hellobar.php
  components/ecommerce/pre/hellobar-vip.php
  components/ecommerce/pre/hellobar.php
  components/hello-bar.php
  components/navbar-reg.php
  components/navbar-unreg.php
  pages/digital-trends/post/ecommerce-registrado.php
  pages/digital-trends/post/ecommerce.php
  pages/digital-trends/post/home-registrado.php
  pages/digital-trends/post/home.php
  pages/digital-trends/post/speaker-interna.php
  pages/digital-trends/pre/home-registrado.php
  pages/digital-trends/pre/home.php
  src/1.0.0/css/components/central-video.css
  src/1.0.0/css/components/companies-list.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/event-numbers.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/premium-content-banner.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/components/users-comments.css
  src/1.0.0/css/general/backgrounds.css
  src/1.0.0/css/general/buttons.css
  src/1.0.0/css/general/variables.css
  src/1.0.0/css/pages/ecommerce.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/js/enums/eventsType.enum.js
  src/img/biblioteca-recursos-2.png
  src/img/home/card-image-digitaltrends-post.png
  src/img/home/card-image-ecommerce-post.png
  src/img/quotes/quote-camila.png
  src/img/quotes/quote-luis.png
  src/img/quotes/quote-martin.png
Labels: size/XXL

#92 DS-5743 refactor: add dynamic event configuration structure & service
  config.php
  services/getCurrentEvent.php
Labels: size/L

#97 DS-5753 Refactor: new router system apply Home DT
  digital-trends-registrado.php
  digital-trends.php
  index.php
  registrado.php
Labels: size/L

#99 DS-5754 Refactor: new router system apply SPONSORS SPEAKERS
  speaker-interna.php
  sponsors-interna.php
  sponsors-registrado.php
  sponsors.php
Labels: size/L

#101 DS-5740 fix images
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/referral.css
  src/img/backgrounds/referral-bg.png
  src/img/ediciones-anteriores/ediciones-anteriores.png
  src/img/referral/referral-people.png
Labels: size/XS

#100 DS-5750 new previous edition
  ediciones-anteriores-registrado.php
  ediciones-anteriores.php
Labels: size/XXL

#106 DS-5756 disabled referal block
  pages/digital-trends/pre/digital-trends-registrado.php
Labels: size/XS

#108 DS-5757 add version query param to utm.js script to prevent caching
  components/footer.php
  config.php
Labels: size/XS

#107 DS-5749 Fix silent failures in Google Sheets integration
  utils/SpreadSheetGoogle.php
  utils/spread/write.php
Labels: size/S

#109 DS-5758 post demo changes
  components/digital-trends/pre/grid-event-types.php
  components/digital-trends/pre/home/hello-module.php
  components/digital-trends/pre/premium-content.php
  components/digital-trends/pre/register-form.php
  components/digital-trends/pre/register-withoutform.php
  components/digital-trends/pre/speakers-carousel.php
  components/digital-trends/pre/users-comments.php
  components/navbar-reg.php
  components/navbar-unreg.php
  components/sponsorsList.php
  pages/digital-trends/pre/digital-trends-registrado.php
  pages/digital-trends/pre/home-registrado.php
  sponsors-promo.php
  src/1.0.0/css/components/doppler-academy-banner.css
  src/1.0.0/css/components/event-cards.css
  src/1.0.0/css/components/hellobar.css
  src/1.0.0/css/components/hero-registration.css
  src/1.0.0/css/components/premium-content-banner.css
  src/1.0.0/css/components/speakers-list.css
  src/1.0.0/css/components/vip-offer.css
  src/1.0.0/css/general/buttons.css
  src/1.0.0/css/pages/home.css
  src/1.0.0/js/commonAnimations.js
  src/1.0.0/js/counterAnimation.js
  src/img/backgrounds/vip-background.png
  src/img/backgrounds/vip-background2.png
  src/img/home/card-image-digitaltrends-post.png
  src/img/home/card-image-ecommerce-post.png
  src/img/icons/icon-check--soft-green-simple.svg
Labels: size/L

#111 DS-5723 fix email template
  utils/relay-templates/dt/dt-pre-template.htm
Labels: size/XS

#121 DS-5773 chore: remove ecommerce old pages
  ecommerce-registrado.php
  ecommerce.php
  pages/digital-trends/during/digital-trends-registrado.php
  pages/digital-trends/during/digital-trends.php
  pages/digital-trends/during/home-registrado.php
  pages/digital-trends/during/home.php
  pages/digital-trends/post/digital-trends-registrado.php
  pages/digital-trends/post/digital-trends.php
  pages/ecommerce/post/ecommerce-registrado.php
  pages/ecommerce/post/ecommerce.php
  pages/ecommerce/post/home-registrado.php
  pages/ecommerce/post/home.php
  pages/ecommerce/post/speaker-interna.php
  pages/ecommerce/pre/ecommerce-registrado.php
  pages/ecommerce/pre/ecommerce.php
  pages/ecommerce/pre/home-registrado.php
  pages/ecommerce/pre/home.php
  pages/sponsors/library-resources.php
Labels: size/L

#122 DS-5777 refactor: migrate checkout to component-based architecture
  .docker/docker-compose.yml
  checkout-success.php
  checkout.php
  components/checkout/checkout-success.php
  components/checkout/checkout.php
  components/digital-trends/checkout/checkout-success.php
  components/digital-trends/checkout/checkout.php
  components/digital-trends/checkout/faq.php
  pages/digital-trends/pre/checkout-success.php
  pages/digital-trends/pre/checkout.php
  stripe/createCustomer.php
Labels: size/XL

#124 DS-5722 modals
  components/modal/modal.css
  components/modal/modal.php
  components/modal/openModal.js
  components/modal/partials/modal-extradata.php
  components/modal/partials/modal-form.php
  components/modal/partials/modal-vip.php
  src/img/backgrounds/bg-moda-vip.png
  src/img/backgrounds/form-modal-bg.png
  src/img/modals/persona-corona.png
Labels: size/L

#125 [DS-5725] Capture and persist emms_ref on registration
  services/register.php
Labels: size/XS

#128 DS-5724 UTM tracking with encoded email
  components/referral.php
  pages/digital-trends/pre/digital-trends-registrado.php
Labels: size/M

#129 DS-5780 unregister captor
  components/modal/modal.css
  components/modal/partials/modal-form.php
  components/register-form-component.php
  pages/digital-trends/pre/digital-trends.php
  src/1.0.0/js/commonForm.js
  src/img/backgrounds/form-modal-bg-1.png
  src/img/modals/computer-men.png
Labels: size/L

#131 DS-5782 modal vip
  components/modal/modal.css
  components/modal/partials/modal-vip.php
  src/img/modals/persona-corona.png
Labels: size/M
